import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { MainHeading, SubHeading } from '../components/Headings';
import Window from '../components/Window';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ele Thompson | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        /* Google Fonts */
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Martel:wght@700&family=Poppins&family=Rambla&family=Roboto+Serif:wght@500&family=Sriracha&display=swap" rel="stylesheet" />
      </Head>

      <main className="container">
        <MainHeading>Ele Thompson</MainHeading>
        <Window className="intro-window">
          I'm a front end developer / software engineer based in Southern California! I like code, keyboards, and cats. <span>♡(•́ω•̀)♡​</span>
        </Window>

        <nav>
          <ul>
            <li><a href="https://www.linkedin.com/in/elevilathompson/" target="_blank">LinkedIn</a></li>
            <li><a href="https://github.com/thompson-ele" target="_blank">GitHub</a></li>
            <li><a href="https://www.instagram.com/keebnewb/" target="_blank">Instagram</a></li>
          </ul>
        </nav>

        <SubHeading>Work Experience</SubHeading>
        <Window heading="REVOLVE">
          <p>I currently work as a UX Front End Developer for REVOLVE, a fashion e-commerce website and brand.</p>
          <p>Things that I love about my job:</p>
          <ul>
            <li>Working on a collaborative team of UX designers and developers</li>
            <li>Making websites that not only look good but are web accessible and performant</li>
            <li>Reviewing other developers code (probably where I learn the most tbh)</li>
            <li>Hunting down bugs 👾</li>
          </ul>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>JavaScript</li>
            <li>jQuery</li>
            <li>Java</li>
          </ul>
        </Window>

        <SubHeading>Projects</SubHeading>
        <p>Portfolio Redesign</p>
        <p>The last time I updated my web portfolio was in 2017 in preparation for my current job.</p>

        <SubHeading>Hobbies</SubHeading>
        <p>In my free time I've been learning electrical engineering and building my own custom mechanical keyboards. If you're interested in 
          what I've been doing checkout my Instagram or Twitch stream.
        </p>

        <SubHeading>Contact</SubHeading>
        <p>The easiest way to contact me is to send me a message through <a href="">LinkedIn</a>!</p>
      </main>
      <footer></footer>
    </div>
  )
}

export default Home
